name: Test

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Versions are upper bounds:
        # "pip install sphinx<8" really installs latest Sphinx 7.x.y
        # "pip install docutils<0.21" really installs latest docutils 0.20.x
        sphinx-version: ["5", "6", "7", "8"]
        docutils-version: ["0.19", "0.20", "0.21"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install "docutils<${{ matrix.docutils-version }}" "sphinx<${{ matrix.sphinx-version }}"

      - name: Build docs
        run: pipx run nox -s docs
